name: Presubmit

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened, labeled]

jobs:
  build-desktop:
    name: build-desktop
    runs-on: ubuntu-latest
    steps:
      # We *only* need to check out the .github/ directory.
      # The check RELEASE_NOTES script uses the GitHub API to verify that RELEASE_NOTES was
      # modified.
      - name: Check out Action
        uses: Bhacaz/checkout-files
        with:
          files: .github/
      - name: Check RELEASE_NOTES
        uses: ./.github/actions/check-release-notes
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ github.event.pull_request.number }}

